# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06c49771dc965b0867db13eca6863da4405217cb349e38aacf63c0076a413f4be0bd76ce4e72f3a87d16228c678a0f0ae973e1e563cb04c4df91e7d3d217ff12

test:
  secret_key_base: 4e64def474087be06ad65550be337f88e0e3cb5702a30238d23b9656ee534efb8bfa515c5f3cd2deefbd251d5fa51dd8c895f1ee3a6c833a6cc88416fdbc9c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
